/** @type {import('tailwindcss').Config} */

const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
    },
    extend: {
      colors: {
        'ef-bg-dim': 'var(--ef-bg-dim)',
        'ef-bg0': 'var(--ef-bg0)',
        'ef-bg1': 'var(--ef-bg1)',
        'ef-bg2': 'var(--ef-bg2)',
        'ef-bg3': 'var(--ef-bg3)',
        'ef-bg4': 'var(--ef-bg4)',
        'ef-bg6': 'var(--ef-bg6)',
        'ef-bg-red': 'var(--ef-bg-red)',
        'ef-bg-visual': 'var(--ef-bg-visual)',
        'ef-bg-yellow': 'var(--ef-bg-yellow)',
        'ef-bg-green': 'var(--ef-bg-green)',
        'ef-bg-blue': 'var(--ef-bg-blue)',
        'ef-red': 'var(--ef-red)',
        'ef-orange': 'var(--ef-orange)',
        'ef-yellow': 'var(--ef-yellow)',
        'ef-green': 'var(--ef-green)',
        'ef-blue': 'var(--ef-blue)',
        'ef-aqua': 'var(--ef-aqua)',
        'ef-purple': 'var(--ef-purple)',
        'ef-fg': 'var(--ef-fg)',
        'ef-gray0': 'var(--ef-gray0)',
        'ef-gray1': 'var(--ef-gray1)',
        'ef-gray2': 'var(--ef-gray2)',
        'award-gold': 'var(--award-gold)',
      },
      typography: ({ theme }) => ({
        aam: {
          css: {
            '--tw-prose-body': theme('colors.ef-fg'),
            '--tw-prose-headings': theme('colors.ef-green'),
            '--tw-prose-lead': theme('colors.ef-aqua'),
            '--tw-prose-links': theme('colors.ef-aqua'),
            '--tw-prose-bold': theme('colors.ef-orange'),
            '--tw-prose-counters': theme('colors.pink[600]'),
            '--tw-prose-bullets': theme('colors.ef-yellow'),
            '--tw-prose-hr': theme('colors.ef-purple'),
            '--tw-prose-quotes': theme('colors.ef-gray0'),
            '--tw-prose-quote-borders': theme('colors.pink[300]'),
            '--tw-prose-captions': theme('colors.pink[700]'),
            '--tw-prose-code': theme('colors.pink[900]'),
            '--tw-prose-pre-code': theme('colors.pink[100]'),
            '--tw-prose-pre-bg': theme('colors.pink[900]'),
            '--tw-prose-th-borders': theme('colors.pink[300]'),
            '--tw-prose-td-borders': theme('colors.pink[200]'),
            '--tw-prose-invert-body': theme('colors.pink[200]'),
            '--tw-prose-invert-headings': theme('colors.white'),
            '--tw-prose-invert-lead': theme('colors.pink[300]'),
            '--tw-prose-invert-links': theme('colors.white'),
            '--tw-prose-invert-bold': theme('colors.white'),
            '--tw-prose-invert-counters': theme('colors.pink[400]'),
            '--tw-prose-invert-bullets': theme('colors.pink[600]'),
            '--tw-prose-invert-hr': theme('colors.pink[700]'),
            '--tw-prose-invert-quotes': theme('colors.pink[100]'),
            '--tw-prose-invert-quote-borders': theme('colors.pink[700]'),
            '--tw-prose-invert-captions': theme('colors.pink[400]'),
            '--tw-prose-invert-code': theme('colors.white'),
            '--tw-prose-invert-pre-code': theme('colors.pink[300]'),
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': theme('colors.pink[600]'),
            '--tw-prose-invert-td-borders': theme('colors.pink[700]'),
          },
        },
      }),
      fontFamily: {
        sans: '-apple-system, BlinkMacSystemFont, "Inter", "IBM Plex Sans", Segoe UI, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol',
      },
    },
  },
  plugins: [require('@tailwindcss/typography', 'tailwindcss-brand-colors')],
};
